config/routes.rb
App::Application.routes.draw do

  devise_for :users, :skip => [:passwords]

  get "forums/search_posts"


  resources  :admins, :only => [:new, :create]

  resource :profile, :only => :show

  resources :users, :only => [:index, :show]  do
    resources :bookmarks, :only => [:create, :destroy]
    member do
      post "ban" => :ban
      post "unban" => :unban
      post "promote" => :promote
      post "demote"  => :demote
    end
  end

  resources :forums, :except => :show do
    resources :topics do
      resources :posts do
        member do
          post :vote
          post :complain
          post :hide
        end
      end
      member do
        post :move
        get :close
        get :open
      end
    end
  end

  root :to => 'forums#index'

end

app/models/forum.rb
class Forum < ActiveRecord::Base

  attr_accessible :description, :name

  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  load_and_authorize_resource

  def index

  end

  def new

  end

  def edit

  end

  def create


    if @forum.save
      redirect_to :action => :index
    else
      render 'new'
    end
  end

  def update


    if @forum.update_attributes(params[:forum])
      redirect_to :action => :index
    else
      render 'edit'
    end
  end

  def destroy

    @forum.destroy

    redirect_to :action => :index
  end

  def search_posts
    @posts = Post.where("body LIKE '%#{params[:search]}%'")
  end

end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/views/forums/_form.html.haml
= form_for(@forum) do |f|
  - if @forum.errors.any?
    #error_explanation
    %h2
    = pluralize(@forum.errors.count, "error")
    prohibited this forum from being saved:
    %ul
    - @forum.errors.full_messages.each do |msg|
      %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/forums/edit.html.haml
%h1>Editing forum

= render 'form'

= link_to 'Back', forums_path

app/views/forums/index.html.haml
- if @breadcrumbs
  - @breadcrumbs[0..-2].each do |txt, path|
    = link_to(h(txt), path)
    >
  = h(@breadcrumbs.last.first)
%br
  %br
    %table.table.table-bordered
      %tr
        %th Forum
        %th Topics
        %th Posts
        %th
        %th
      = form_tag ('/forums/search_posts'), :method => :get do
        %p Search posts
        = text_field_tag :search, params[:search]
        = submit_tag "Filter", :class => "btn btn-primary"
      - @forums.each do |forum|
        %tr
          %td
            %h4= link_to forum.name, forum_topics_path(forum.id)
            %small
              = forum.description
          %td= forum.topics.count
          %td= forum.posts.count
          - if can? :update, forum
            %td= link_to 'Edit', edit_forum_path(forum)
          - if can? :destroy, forum
            %td= link_to 'Destroy', forum, method: :delete, data: { confirm: 'Are you sure?' }
    %br/
    - if can? :create, Forum
      = link_to 'New Forum', new_forum_path

app/views/forums/new.html.haml
%h1 New forum

= render 'form'

= link_to 'Back', forums_path

app/views/forums/search_posts.html.haml
%table.table
  %tr
    %th{:width => "300px"} User
    %th Body
  - @posts.each do |post|
    %tr
      %td
        %p
          %b
            Nickname:#{link_to post.user.nickname, post.user}
        %div{:style => "line-height: 4pt"}
          %p
            Role:
            - if post.user.has_role? :admin
              Admin
            -else
              - if post.user.has_role? :moderator
                Moderator
              - else
                User
          %p
            Registration date:
            \#{post.user.created_at.to_formatted_s(:long)}
          %p
            Posts::
            \#{post.user.posts.count}
      %td
        %p= post.created_at.to_formatted_s(:short)
        %p
          = post.body