config/routes.rb
App::Application.routes.draw do

  devise_for :users, :skip => [:passwords]

  get "forums/search_posts"


  resources  :admins, :only => [:new, :create]

  resource :profile, :only => :show

  resources :users, :only => [:index, :show]  do
    resources :bookmarks, :only => [:create, :destroy]
    member do
      post "ban" => :ban
      post "unban" => :unban
      post "promote" => :promote
      post "demote"  => :demote
    end
  end

  resources :forums, :except => :show do
    resources :topics do
      resources :posts do
        member do
          post :vote
          post :complain
          post :hide
        end
      end
      member do
        post :move
        get :close
        get :open
      end
    end
  end

  root :to => 'forums#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

       user ||= User.new

       cannot :read, UsersController

        if user.has_role? :admin
         can :manage, [Post,Topic,Forum]


       else
         can :read, :all

         if user.has_role? :user
           can :create, [Topic, Post]
           can [:update, :destroy], [Topic, Post] do |smth|
             smth.try(:user) == user
           end
         end

         if user.has_role? :moderator
           can :manage, [Post, Topic]
           cannot :destroy, Topic
         end
       end

  end
end

app/models/ban.rb
class Ban < ActiveRecord::Base

  attr_accessible :expires_at, :reason

  belongs_to :user

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

  belongs_to :user
  belongs_to :topic

end

app/models/complain.rb
class Complain < ActiveRecord::Base

  attr_accessible :reason

  belongs_to :user
  belongs_to :post

end

app/models/forum.rb
class Forum < ActiveRecord::Base

  attr_accessible :description, :name

  has_many :topics, :dependent => :destroy
  has_many :posts, :through => :topics

end

app/models/post.rb
class Post < ActiveRecord::Base

  attr_accessible :body

  belongs_to :topic
  belongs_to :user

  has_many :complains
  has_many :votes

  validates_presence_of :body

  self.per_page = 4

  scope :published, where(:note => false)
  scope :unpublished, where(:note => true)
  scope :complained, where(:complained => true)


end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name

  has_many :users_roles
  has_many :users, :through => :users_roles
end

app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessible :name, :forum_id

  belongs_to :user
  belongs_to :forum

  has_many :posts

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  attr_accessible :email, :password, :nickname, :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar, :role_ids, :roles

  has_many :posts
  has_many :topics
  has_many :bookmarks
  has_many :notes
  has_one :ban
  has_many :users_roles
  has_many :roles, :through => :users_roles

  scope :bannable, includes(:roles).where(:roles => {:id => 1})


  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end


end

app/models/users_role.rb
class UsersRole < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
   attr_accessible :user_id, :role_id
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  belongs_to :user
  belongs_to :post

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  load_and_authorize_resource :forum
  load_and_authorize_resource :topic, :through => :forum
  load_and_authorize_resource :post, :through => :topic, :except => [:vote, :complain]

  before_filter :authenticate_user!

  def new

  end

  def create
    if Topic.exists?(params[:topic_id])

      @post.user = current_user

      if params[:reply]
        @post.note = false
      end

      if params[:note]
        @post.note = true
      end

    else
      redirect_to(forums_path, :notice =>"Please specify a valid forum")
    end

    if @post.save
      redirect_to(forum_topic_path(@forum,@topic), :notice => 'Your reply was posted')
    else
      render 'new'
    end
  end

  def edit



    @topic = @post.topic
    @forum =  @topic.forum

  end

  def update

    if @post.update_attributes(params[:post])
      redirect_to forum_topic_path(params[:forum_id], params[:topic_id])
    else
      render 'edit'
    end
  end

  def destroy

      @post.body = 'Deleted'
      @post.save

      redirect_to forum_topic_path(params[:forum_id], params[:topic_id])

  end

  def vote
    authenticate_user!
   @post = Post.find(params[:id])

    if @post.votes.where(user_id: current_user.id).exists?
      flash[:error] = "Sorry, you have already voted"
      redirect_to :back
    else
      @post.increment(:rating)
      @post.save

      @vote = Vote.new(params[:vote])
      @vote.user = current_user
      @vote.post = @post
      @vote.save

      redirect_to :back, :notice => "Voted successfully"
    end
  end

  def complain
    authenticate_user!
    @post = Post.find(params[:id])

    if @post.complains.where(user_id: current_user.id).exists?
      flash[:error] = "Sorry, you have already complained"
      redirect_to :back
    else
      @post.complained = true

      @complain = Complain.new(params[:complain])
      @complain.user = current_user
      @complain.post = @post

      if @post.save && @complain.save
        redirect_to :back, :notice => "Complained successfully"
      else
        flash[:error] = "Smth went wrong"
        redirect_to :back
      end
    end
  end

  def hide
    if current_user.has_role? :admin
      @post = Post.find(params[:id])
      @post.complained = false

      if @post.save
        redirect_to :back, :notice => "Hided successfully"
      else
        flash[:error] = "Smth went wrong"
        redirect_to :back
      end
    else
      flash[:error] = "You dont have permission"
      redirect_to :back
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/forums_helper.rb
module ForumsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admins/new.html.haml
%h1 Creating new admin
= form_for @user, :url => admins_path do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - for message in @user.errors.full_messages
          %li= message
  %p
    = f.label :nickname
    %br/
    = f.text_field :nickname
  %p
    = f.label :avatar
    = image_tag(@user.avatar.thumb.url) if @user.avatar?
    %br/
    = f.file_field :avatar
    = f.hidden_field :avatar_cache
  %p
    = f.label :email
    %br/
    = f.text_field :email
  %p
    = f.label :password
    %br/
    = f.password_field :password
  %p
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %p.button= f.submit

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
    %a.close{"data-dismiss" => "alert"} ×
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/layouts/_navigation.html.haml
= link_to "Home", root_path, :class => 'brand'
%ul.nav
  - if user_signed_in?
    %li
      = link_to('All users', users_path)
    %li
      = link_to('Profile', profile_path)
  - else
    %li
      = link_to "Sign up", new_user_registration_path
  - if user_signed_in?
    %li
      = link_to "Log out", destroy_user_session_path, method: :delete
  - else
    %li
      = link_to "Log in", new_user_session_path
  -if user_signed_in? && current_user.has_role?(:admin)
    %li
      = link_to 'Create new admin', new_admin_path
  %li
    Users online: #{counter}

app/views/layouts/application.html.haml
<!doctype html>
%html
  %head
    %meta{:charset => "utf-8"}
      %meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}
        %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
          %title= content_for?(:title) ? yield(:title) : "Forum"
          %meta{:content => "", :name => "description"}
            %meta{:content => "", :name => "author"}
              = stylesheet_link_tag    "application", :media => "all"
              = javascript_include_tag "application"
              = csrf_meta_tags
              = yield(:head)
  %body
    %header.navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .content
          .row
            .span12
              = render 'layouts/messages'
              = yield
          %footer