config/routes.rb
App::Application.routes.draw do

  devise_for :users, :skip => [:passwords]

  get "forums/search_posts"


  resources  :admins, :only => [:new, :create]

  resource :profile, :only => :show

  resources :users, :only => [:index, :show]  do
    resources :bookmarks, :only => [:create, :destroy]
    member do
      post "ban" => :ban
      post "unban" => :unban
      post "promote" => :promote
      post "demote"  => :demote
    end
  end

  resources :forums, :except => :show do
    resources :topics do
      resources :posts do
        member do
          post :vote
          post :complain
          post :hide
        end
      end
      member do
        post :move
        get :close
        get :open
      end
    end
  end

  root :to => 'forums#index'

end

app/models/topic.rb
class Topic < ActiveRecord::Base

  attr_accessible :name, :forum_id

  belongs_to :user
  belongs_to :forum

  has_many :posts

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  load_and_authorize_resource :forum
  load_and_authorize_resource :topic, :through => :forum

  before_filter :authenticate_user!, :except => [:index, :show]


  def index
    add_breadcrumb @forum.name, forum_topics_path(@forum)
  end

  def new
    @post = @topic.posts.build
  end

  def create
    @post = @topic.posts.build(params[:post])
    @post.note = false
    @topic.user = @post.user = current_user

    if @topic.save
      redirect_to :action => :index
    else
      render 'new'
    end
  end

  def show
    @forums = Forum.all

    if params[:search].present?
      @posts = @topic.posts.published.where("body LIKE '%#{params[:search]}%'") .paginate(:page => params[:page])
    else
      @posts = @topic.posts.published.paginate(:page => params[:page])
    end

    add_breadcrumb @forum.name, forum_topics_path(@forum)
    add_breadcrumb @topic.name, forum_topic_path(@forum,@topic)
  end

  def edit
    @post = @topic.posts.first

  end

  def update

    if @topic.update_attributes(params[:topic])
      redirect_to :action => :index
    else
      render 'edit'
    end
  end

  def close
    @topic.closed = true

    if @topic.save
      redirect_to :back, :notice => "Topic is closed"
    else
      flash[:error] = 'Smth went wrong'
      redirect_to :back
    end
  end

  def open
    @topic.closed = false

    if @topic.save
      redirect_to :back, :notice => "Topic is opened"
    else
      flash[:error] = 'Smth went wrong'
      redirect_to :back
    end
  end

  def destroy

      @topic.destroy
      redirect_to :action => :index

  end

  def move
    @topic = Topic.find(params[:id])
    @topic.update_attributes(params[:topic])

    redirect_to root_url, :notice => "Topic is moved"
  end


end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/edit.html.haml
%h1 Editing topic
= form_for(@topic, :url => forum_topic_path(@forum)) do |f|
- if @topic.errors.any?
#error_explanation
%h2
= pluralize(@topic.errors.count, "error")
prohibited this topic from being saved:
%ul
- @topic.errors.full_messages.each do |msg|
%li= msg
.field
= f.label :name
%br/
= f.text_field :name
= fields_for(@post) do |f|
.field
= f.label :body
%br/
= f.text_area(:body, :size => "60x10")
.actions
= f.submit
= link_to 'Show', [@forum,@topic]
|
\#{link_to 'Back', forum_topics_path}

app/views/topics/index.html.haml
%br
  %p
    - if @breadcrumbs
      - @breadcrumbs[0..-2].each do |txt, path|
        = link_to(h(txt), path)
        >
      = h(@breadcrumbs.last.first)
  %br
    %table.table
      %tr
        %th Name
        %th Author
        %th Last Reply
        %th Replies
        %th
        %th
      - @topics.each do |topic|
        %tr
          %td= link_to topic.name, forum_topic_path(@forum,topic)
          %td= link_to topic.user.nickname, topic.user
          %td
            = distance_of_time_in_words_to_now topic.posts.find(:last).created_at
            %br/
            ago by #{link_to topic.posts.find(:last).user.nickname, topic.posts.find(:last).user}
          %td= topic.posts.count - 1
          - if can? :update, topic
            %td= link_to 'Edit', edit_forum_topic_path(@forum,topic)
          - if can? :destroy, topic
            %td= link_to 'Destroy', [@forum,topic], :confirm => 'Are you sure?', :method => :delete
    %br/
    - if can? :create, Topic
      = link_to 'New Topic', new_forum_topic_path

app/views/topics/new.html.haml
%h1#page_title New topic
= form_for(@topic, :url => forum_topics_path) do |f|
  - if @topic.errors.any?
    #error_explanation
      %h2
        = pluralize(@topic.errors.count, "error")
        prohibited this topic from being saved:
      %ul
        - @topic.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    %br/
    = f.text_field :name
  = fields_for(@post) do |f|
    .field
      = f.label :body
      %br/
      = f.text_area(:body, :size => "60x10")
  .actions
    = f.submit :as => "Create Post"

app/views/topics/show.html.haml
%table.table
  %tr
    %th
      %p
        - if @breadcrumbs
          - @breadcrumbs[0..-2].each do |txt, path|
            = link_to(h(txt), path)
            >
          = h(@breadcrumbs.last.first)
    %th
      = form_tag forum_topic_path(@forum,@topic), :method => :get do
        %p Search
        = text_field_tag :search, params[:search]
        = submit_tag "Filter", :class => "btn btn-primary"
    %th
      - if user_signed_in?
        = form_tag user_bookmarks_path(current_user, :topic => @topic) do
          = submit_tag "Add to bookmarks", :class => "btn btn-primary"
%table.table
  %tr
    %th{:width => "300px"} User
    %th Body
  - @posts.each do |post|
    %tr
      %td
        %p
          %b
            Nickname:#{link_to post.user.nickname, post.user}
        %p
          = image_tag(post.user.avatar.thumb.url, :alt => "Avatar", :class => "avatar round") if post.user.avatar?
        %div{:style => "line-height: 4pt"}
          %p
            Registration date:
            \#{post.user.created_at.to_formatted_s(:long)}
          %p
            Posts::
            \#{post.user.posts.count}
      %td
        %p= post.created_at.to_formatted_s(:short)
        %p
          = post.body
        - if user_signed_in?
          = link_to 'Vote', vote_forum_topic_post_path(@forum,@topic,post), method: :post
          = link_to 'Complain', complain_forum_topic_post_path(@forum,@topic,post), method: :post
        - if can? :update, post
          = link_to 'Edit', edit_forum_topic_post_path(@forum,@topic,post)
        - if can? :destroy, post
          = link_to 'Destroy', [@forum,@topic,post], :confirm => 'Are you sure?', :method => :delete
= will_paginate @posts
- if user_signed_in?
  = link_to 'Reply', new_forum_topic_post_path(:forum=>@forum.id, :topic_id=>@topic.id)
- else
  = link_to 'Reply', new_user_session_path
|
- if user_signed_in? && current_user.has_role?(:admin)
  - if @topic.closed?
    = link_to 'Reopen topic', :action => :open, :forum_id => @forum.id, :id => @topic.id
  - else
    = link_to 'Close topic', :action => :close,  :forum_id => @forum.id, :id => @topic.id
  = form_for :topic, url: move_forum_topic_path(@forum,@topic) do |f|
    = f.collection_select :forum_id, @forums, :id, :name, {:include_blank => 'Please Select'}
    = f.submit "Move topic", class: "btn btn-primary"

= link_to 'Back', forum_topics_path