config/routes.rb
App::Application.routes.draw do

  devise_for :users, :skip => [:passwords]

  get "forums/search_posts"


  resources  :admins, :only => [:new, :create]

  resource :profile, :only => :show

  resources :users, :only => [:index, :show]  do
    resources :bookmarks, :only => [:create, :destroy]
    member do
      post "ban" => :ban
      post "unban" => :unban
      post "promote" => :promote
      post "demote"  => :demote
    end
  end

  resources :forums, :except => :show do
    resources :topics do
      resources :posts do
        member do
          post :vote
          post :complain
          post :hide
        end
      end
      member do
        post :move
        get :close
        get :open
      end
    end
  end

  root :to => 'forums#index'

end

app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  attr_accessible :email, :password, :nickname, :password_confirmation, :remember_me, :avatar, :avatar_cache, :remove_avatar, :role_ids, :roles

  has_many :posts
  has_many :topics
  has_many :bookmarks
  has_many :notes
  has_one :ban
  has_many :users_roles
  has_many :roles, :through => :users_roles

  scope :bannable, includes(:roles).where(:roles => {:id => 1})


  def has_role?(role_sym)
    roles.any? { |r| r.name.underscore.to_sym == role_sym }
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

 before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def ban
    @user = User.find(params[:id])

    if !@user.ban && current_user.has_role?(:admin) && !@user.has_role?(:admin)
      @ban = Ban.new(params[:ban])
      @ban.expires_at = Time.now() + Integer(params[:time]).days
      @ban.user_id = @user.id

      if @ban.save
        redirect_to :back, :notice => "Successfully banned"
       else
        flash[:error] = "Smth went wrong"
       end
    else
      flash[:error] = "You can't ban this user'"
      redirect_to root_url
    end
  end

  def unban
    @user = User.find(params[:id])

    if @user.ban && current_user.has_role?(:admin)
       @user.ban.destroy
      redirect_to :back, :notice => "Successfully unbanned"
    else
      flash[:error] = "You can't unban this user'"
      redirect_to root_url
    end
  end


 def promote
   @user = User.find(params[:id])

   if  current_user.has_role?(:admin) && @user.has_role?(:user) && !@user.has_role?(:moderator)

      @role = UsersRole.new(:user_id => @user.id, :role_id => 2 )

      if @role.save
        redirect_to :back, :notice => "Successfully promoted"
      else
        flash[:error] = "Smth went wrong"
        redirect_to :back
     end

   else
     flash[:error] = "You can't promote this user'"
     redirect_to root_url
   end


 end

 def demote
   @user = User.find(params[:id])

 if  current_user.has_role?(:admin) && @user.has_role?(:moderator)


   @role = UsersRole.find_by_user_id_and_role_id(@user.id, 2)

   if @role && @role.destroy
     redirect_to :back, :notice => "Successfully demoted"
   else
     flash[:error] = "Smth went wrong"
     redirect_to :back
   end

 else
    flash[:error] = "You can't demote this user'"
    redirect_to root_url
 end

end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.haml
%table.table
  %tr
    %th User id
    %th Nickname
    %th Permission level
    %th
    %th
    %th
    %th
  - @users.each do |user|
    %tr
      %td= user.id
      %td= user.nickname
      %td
        - if user.has_role? :admin
          admin
        - else
          - if user.has_role? :moderator
            moderator
          - else
            user
      %td= link_to 'View profile', :action => :show, :id => user.id
      - if  current_user.has_role?(:admin) && user.has_role?(:user) && !user.has_role?(:moderator)
        %td= link_to 'Promote to moderator', promote_user_path(user), :method => :post
      - if  current_user.has_role?(:admin) && user.has_role?(:moderator)
        %td= link_to 'Demote', demote_user_path(user), :method => :post
      %td
        - if  !user.ban && current_user.has_role?(:admin) && !user.has_role?(:admin)
          = form_for Ban.new, :url => ban_user_path(user) do |f|
            %p
              = f.label :reason
              %br/
              = f.text_field :reason
            %p
              = select_tag "time", options_for_select([["select" , "0" ], ["one day", "1"], ["three days", "3"], ["one week", "7"], ["forever", "500"]])
            = f.submit :class => "btn btn-danger"
      %td
        - if  current_user.has_role?(:admin) && user.ban && user.ban.expires_at > DateTime.now.to_date
          %p
            Banned till #{user.ban.expires_at}. Reason : #{user.ban.reason}
          = form_tag unban_user_path(user) do
            = submit_tag "Unban", :class => "btn btn-success"

app/views/users/show.html.haml
%h3
  = @user.nickname
  's profile:
%br
  %p
    = image_tag(@user.avatar.thumb.url, :alt => "Avatar", :class => "avatar round") if @user.avatar?
  %p
    %strong User id
    = @user.id
  %p
    %strong Registration date
    = @user.created_at.to_formatted_s(:long)
  %p
    %strong Nickname
    = @user.nickname
  %p
    %strong Topics
    = @user.topics.count
  %p
    %strong Posts
    = @user.posts.count
  %p
    %strong Rating
    = @user.posts.sum(:rating)